### ISSUE TITLE
Can't click the video link

### ISSUE THREAD

**Issue by siba2893** [wmmc/codeschool-video-downloader#11]
When the code fetches and iterate over 
`links = @browser.links(:class, "js-level-open")`
if you try to click them, nothing happen, if you let your code that is
`course.when_present.fire_event('click')`
will result in 
"#<Selenium::WebDriver::Error::JavascriptError: Error: Permission denied to access property \"x\">"

**Comment by will-clarke** [comment]
This has been updated now; should be working. 

Let me know if there's still a problem!
