### ISSUE TITLE
#<NoMethodError: undefined method `attributes' for nil:NilClass>

### ISSUE THREAD

**Issue by ghost** [wmmc/codeschool-video-downloader#2]
Hello.
I have such issue:

"http://www.codeschool.com/screencasts/emberscreencasts-es2015-functions-minus-functions"
NoMethodError: undefined method `attributes' for nil:NilClass

How to solve this one? No videos are being downloaded. with this error...

**Comment by ghost** [comment]
Ok, Im totally "green" with Ruby. But I figured out how to fix this. As far as I see the structure must have changed.

So now I changed the line:

url = link.children[3].attributes['src'].value

to:  url = link.children[0].children[0].attributes['src'].value

and videos are downloading well : ]

**Comment by will-clarke** [comment]
Thanks for fixing this - I haven't looked at this for a while so it's good to know that with your fix it's still working!
I've merged this into master now. :smiley:
