### ISSUE TITLE
#<NoMethodError: undefined method `value' for nil:NilClass>

### ISSUE THREAD

**Issue by ghost** [wmmc/codeschool-video-downloader#3]
Unfortunately these two bugs appear while downloading courses (I fixed screencasts last time):

NoMethodError: undefined method `children' for nil:NilClass
NoMethodError: undefined method`value' for nil:NilClass

I checked it, trying to fix of course, but can't find out how to make a loop on all "a" elements with clicking/running event bound to this "a", to open a video, in order to download. These videos are grouped into links, and source urls are not available. URLs are being bound to this "a" dynamically, after clicking and opening single video popup/modal window.

damn... can anybody help with this ? : )

**Comment by sudoliyang** [comment]
have same problem.

**Comment by will-clarke** [comment]
This should have been closed by the latest pull request from @vecerek :+1:
Let me know if this is still an issue.

**Comment by sudoliyang** [comment]
it is still issue

Sincerely
-Liyang

**Comment by vecerek** [comment]
@sudoliyang hmm, really? If you had a look at the new code, no 'children' method is being invoked anymore. Could you add the error msg here, please?

**Comment by sudoliyang** [comment]
Thank you vecerek.

```
Course
"https://www.codeschool.com/courses/try-ember/videos"

Opening video...
Videos left 6
URL retrieved
Closing video...
Downloading video 1 - Getting Started...
"#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>"
Opening video...
Videos left 5
URL retrieved
Closing video...
Downloading video 2 - Templates and the Router...
"#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>"
```

**Comment by vecerek** [comment]
It seems like your SSL is outdated. Follow the [instructions](http://railsapps.github.io/openssl-certificate-verify-failed.html) to fix it :)

**Comment by sudoliyang** [comment]
Thank you very much!
