### ISSUE TITLE
"#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>"

### ISSUE THREAD

**Issue by cheesefinger** [wmmc/codeschool-video-downloader#7]
Opening video...
Videos left 7
URL retrieved
Closing video...
Downloading video 1 - Writing Your First React Component...
"#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>"

**Comment by will-clarke** [comment]
Try this (as suggested by @vecerek): Your SSL may be outdated. Follow the [instructions](http://railsapps.github.io/openssl-certificate-verify-failed.html) to fix it :)
