### ISSUE TITLE
Unable to find Mozilla geckodriver.

### ISSUE THREAD

**Issue by akshaybharwani** [wmmc/codeschool-video-downloader#9]
Throws me this error when I try to run the last command. Sends me to download the [latest release](https://github.com/mozilla/geckodriver/releases). Downloaded it, don't know what to do next.

**Comment by N4d4** [comment]
same problem.

**Comment by effexts** [comment]
Read carefully the error. It shows you the solution itself. Download Mozilla geckodriver.

**Comment by akshaybharwani** [comment]
I did. But where to put it? The error just specifies PATH and nothing else.

**Comment by effexts** [comment]
In any folder of your path. The executable geckodriver needs to be recognized by the terminal/console.

**Comment by will-clarke** [comment]
I've updated this, so should be working a bit better now...
Remember to `brew install chromedriver` to sidestep this issue...
😃
